{
    "type": "bundle",
    "id": "bundle--fe723b9b-bc03-4d96-8ef4-149cad4ea849",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--939aa02e-cedc-49e6-9e85-a61d352fd517",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-07T00:15:00.000Z",
            "modified": "2022-11-08T15:03:00.000Z",
            "name": "CVE-2022-42919",
            "description": "Python 3.9.x and 3.10.x through 3.10.8 on Linux allows local privilege escalation in a non-default configuration. The Python multiprocessing library, when used with the forkserver start method on Linux, allows pickles to be deserialized from any user in the same machine local network namespace, which in many system configurations means any user on the same machine. Pickles can execute arbitrary code. Thus, this allows for local user privilege escalation to the user that any forkserver process is running as. Setting multiprocessing.util.abstract_sockets_supported to False is a workaround. The forkserver start method for multiprocessing is not the default start method. This issue is Linux specific because only Linux supports abstract namespace sockets. CPython before 3.9 does not make use of Linux abstract namespace sockets by default. Support for users manually specifying an abstract namespace socket was added as a bugfix in 3.7.8 and 3.8.4, but users would need to make specific uncommon API calls in order to do that in CPython before 3.9.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-42919"
                },
                {
                    "source_name": "cwe",
                    "external_id": "NVD-CWE-noinfo"
                },
                {
                    "source_name": "https://github.com/python/cpython/issues/97514",
                    "url": "https://github.com/python/cpython/issues/97514"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2022-42919",
                            "ASSIGNER": "cve@mitre.org"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "NVD-CWE-noinfo"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://github.com/python/cpython/issues/97514",
                                    "name": "https://github.com/python/cpython/issues/97514",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Third Party Advisory"
                                    ]
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "Python 3.9.x and 3.10.x through 3.10.8 on Linux allows local privilege escalation in a non-default configuration. The Python multiprocessing library, when used with the forkserver start method on Linux, allows pickles to be deserialized from any user in the same machine local network namespace, which in many system configurations means any user on the same machine. Pickles can execute arbitrary code. Thus, this allows for local user privilege escalation to the user that any forkserver process is running as. Setting multiprocessing.util.abstract_sockets_supported to False is a workaround. The forkserver start method for multiprocessing is not the default start method. This issue is Linux specific because only Linux supports abstract namespace sockets. CPython before 3.9 does not make use of Linux abstract namespace sockets by default. Support for users manually specifying an abstract namespace socket was added as a bugfix in 3.7.8 and 3.8.4, but users would need to make specific uncommon API calls in order to do that in CPython before 3.9."
                                }
                            ]
                        }
                    },
                    "impact": {
                        "baseMetricV3": {
                            "cvssV3": {
                                "version": "3.1",
                                "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                                "attackVector": "LOCAL",
                                "attackComplexity": "LOW",
                                "privilegesRequired": "LOW",
                                "userInteraction": "NONE",
                                "scope": "UNCHANGED",
                                "confidentialityImpact": "HIGH",
                                "integrityImpact": "HIGH",
                                "availabilityImpact": "HIGH",
                                "baseScore": 7.8,
                                "baseSeverity": "HIGH"
                            },
                            "exploitabilityScore": 1.8,
                            "impactScore": 5.9
                        }
                    },
                    "publishedDate": "2022-11-07T00:15Z",
                    "lastModifiedDate": "2022-11-08T15:03Z"
                }
            }
        },
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--3cde18f3-a6f5-4a40-a558-c35da845deec",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-07T00:15:00.000Z",
            "modified": "2022-11-08T15:03:00.000Z",
            "name": "CVE-2022-42919",
            "description": "Python 3.9.x and 3.10.x through 3.10.8 on Linux allows local privilege escalation in a non-default configuration. The Python multiprocessing library, when used with the forkserver start method on Linux, allows pickles to be deserialized from any user in the same machine local network namespace, which in many system configurations means any user on the same machine. Pickles can execute arbitrary code. Thus, this allows for local user privilege escalation to the user that any forkserver process is running as. Setting multiprocessing.util.abstract_sockets_supported to False is a workaround. The forkserver start method for multiprocessing is not the default start method. This issue is Linux specific because only Linux supports abstract namespace sockets. CPython before 3.9 does not make use of Linux abstract namespace sockets by default. Support for users manually specifying an abstract namespace socket was added as a bugfix in 3.7.8 and 3.8.4, but users would need to make specific uncommon API calls in order to do that in CPython before 3.9.",
            "indicator_types": [
                "compromised"
            ],
            "pattern": "[(software:cpe='cpe:2.3:a:python:python:*:*:*:*:*:*:*:*')]",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2022-11-07T00:15:00Z",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
                    "extension_type": "property-extension",
                    "all_cpe23uris": [
                        "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                    ],
                    "vulnerable_cpeid": [
                        "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
                    ]
                }
            }
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--10aa6176-68aa-48ac-b867-8f77f6ad0e39",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-07T00:15:00.000Z",
            "modified": "2022-11-08T15:03:00.000Z",
            "relationship_type": "identifies",
            "source_ref": "indicator--3cde18f3-a6f5-4a40-a558-c35da845deec",
            "target_ref": "vulnerability--939aa02e-cedc-49e6-9e85-a61d352fd517",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ]
        }
    ]
}