{
    "type": "bundle",
    "id": "bundle--3dcf0675-e6a2-4227-932e-e88622a0143b",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--39a46906-9657-4417-859e-3bc8130f93bd",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2020-12-22T17:15:00.000Z",
            "modified": "2022-07-25T18:15:00.000Z",
            "name": "CVE-2020-29396",
            "description": "A sandboxing issue in Odoo Community 11.0 through 13.0 and Odoo Enterprise 11.0 through 13.0, when running with Python 3.6 or later, allows remote authenticated users to execute arbitrary code, leading to privilege escalation.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-29396"
                },
                {
                    "source_name": "cwe",
                    "external_id": "NVD-CWE-noinfo"
                },
                {
                    "source_name": "https://github.com/odoo/odoo/issues/63712",
                    "url": "https://github.com/odoo/odoo/issues/63712"
                },
                {
                    "source_name": "N/A",
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2020-29396",
                            "ASSIGNER": "security@odoo.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "NVD-CWE-noinfo"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://github.com/odoo/odoo/issues/63712",
                                    "name": "https://github.com/odoo/odoo/issues/63712",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Patch",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html",
                                    "name": "N/A",
                                    "refsource": "N/A",
                                    "tags": []
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "A sandboxing issue in Odoo Community 11.0 through 13.0 and Odoo Enterprise 11.0 through 13.0, when running with Python 3.6 or later, allows remote authenticated users to execute arbitrary code, leading to privilege escalation."
                                }
                            ]
                        }
                    },
                    "impact": {
                        "baseMetricV3": {
                            "cvssV3": {
                                "version": "3.1",
                                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                                "attackVector": "NETWORK",
                                "attackComplexity": "LOW",
                                "privilegesRequired": "LOW",
                                "userInteraction": "NONE",
                                "scope": "UNCHANGED",
                                "confidentialityImpact": "HIGH",
                                "integrityImpact": "HIGH",
                                "availabilityImpact": "HIGH",
                                "baseScore": 8.8,
                                "baseSeverity": "HIGH"
                            },
                            "exploitabilityScore": 2.8,
                            "impactScore": 5.9
                        },
                        "baseMetricV2": {
                            "cvssV2": {
                                "version": "2.0",
                                "vectorString": "AV:N/AC:L/Au:S/C:P/I:P/A:P",
                                "accessVector": "NETWORK",
                                "accessComplexity": "LOW",
                                "authentication": "SINGLE",
                                "confidentialityImpact": "PARTIAL",
                                "integrityImpact": "PARTIAL",
                                "availabilityImpact": "PARTIAL",
                                "baseScore": 6.5
                            },
                            "severity": "MEDIUM",
                            "exploitabilityScore": 8.0,
                            "impactScore": 6.4,
                            "acInsufInfo": false,
                            "obtainAllPrivilege": false,
                            "obtainUserPrivilege": false,
                            "obtainOtherPrivilege": false,
                            "userInteractionRequired": false
                        }
                    },
                    "publishedDate": "2020-12-22T17:15Z",
                    "lastModifiedDate": "2022-07-25T18:15Z"
                }
            }
        },
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--48c9b0dd-fbf7-4684-9d5c-5b9bf45df721",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2020-12-22T17:15:00.000Z",
            "modified": "2022-07-25T18:15:00.000Z",
            "name": "CVE-2020-29396",
            "description": "A sandboxing issue in Odoo Community 11.0 through 13.0 and Odoo Enterprise 11.0 through 13.0, when running with Python 3.6 or later, allows remote authenticated users to execute arbitrary code, leading to privilege escalation.",
            "indicator_types": [
                "compromised"
            ],
            "pattern": "[((software:cpe='cpe:2.3:a:odoo:odoo:*:*:*:*:community:*:*:*' OR software:cpe='cpe:2.3:a:odoo:odoo:*:*:*:*:enterprise:*:*:*') AND (software:cpe='cpe:2.3:a:python:python:*:*:*:*:*:*:*:*'))]",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2020-12-22T17:15:00Z",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
                    "extension_type": "property-extension",
                    "all_cpe23uris": [
                        "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                        "cpe:2.3:a:odoo:odoo:*:*:*:*:enterprise:*:*:*",
                        "cpe:2.3:a:odoo:odoo:*:*:*:*:community:*:*:*"
                    ],
                    "vulnerable_cpeid": [
                        "cpe:2.3:a:odoo:odoo:*:*:*:*:enterprise:*:*:*",
                        "cpe:2.3:a:odoo:odoo:*:*:*:*:community:*:*:*"
                    ]
                }
            }
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--0f286d74-eb8e-4a5e-a6ae-8c66efc74e6e",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2020-12-22T17:15:00.000Z",
            "modified": "2022-07-25T18:15:00.000Z",
            "relationship_type": "identifies",
            "source_ref": "indicator--48c9b0dd-fbf7-4684-9d5c-5b9bf45df721",
            "target_ref": "vulnerability--39a46906-9657-4417-859e-3bc8130f93bd",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ]
        }
    ]
}